### PR TITLE
Add RAW Option support to Lite Client

### PR DESCRIPTION
**Pull request by marjohn56**
Just added the raw option bits.

### CODE REVIEW

**Comment by fichtner** [comment]
how does this differ from https://github.com/opnsense/dhcp6c/commit/a716d4bf ?

**Comment by marjohn56** [comment]
I've just imported the needed bits. I couldn't get the raw branch to play ball for some reason.

**Comment by fichtner** [comment]
okay so drop the branch and use this as it's verified?

**Comment by marjohn56** [comment]
Yes that's the idea. I've taken the changes directly from the working raw version source.

**Comment by fichtner** [comment]
Merged manually in e36db7ea, the two c files included are auto-generated... ;) Thanks!

**Pull request closed without merging**
