### PR TITLE
dhcp6c MIA

### PR DESCRIPTION
**Pull request by marjohn56**
Seems config.c missed the bus...

### CODE REVIEW

**Comment by fichtner** [comment]
Merged, thanks!

What do you make of the changes in dhcp6c.c that were not in the original patch? Do we need those?

```
diff --git a/dhcp6c.c b/dhcp6c.c
index 490bd97..93838c7 100644
--- a/dhcp6c.c
+++ b/dhcp6c.c
@@ -922,7 +922,6 @@ client6_send(struct dhcp6_event *ev)
 	struct dhcp6_optinfo optinfo;
 	ssize_t optlen, len;
 	struct dhcp6_eventdata *evd;
-	struct rawoption *rawop;
 
 	ifp = ev->ifp;
 
@@ -1082,10 +1081,6 @@ client6_send(struct dhcp6_event *ev)
 		goto end;
 	}
 
-	/* XXX */
-	rawop_clear_list(&optinfo.rawops);
-	rawop_copy_list(&optinfo.rawops, &ifp->rawops);
-
 	/* set options in the message */
 	if ((optlen = dhcp6_set_options(dh6->dh6_msgtype,
 	    (struct dhcp6opt *)(dh6 + 1),
```

**Comment by marjohn56** [comment]
I'm about to compile the current master with the missing config.c, I'll get Kev to test it. I suspect we need those too. Bit alarmed I seemed to have missed these on the original PR.

**Comment by fichtner** [comment]
Just to clarify: the diff is reversed. master has these dhcp6c.c changes and the RAW ports option didn't.

**Comment by marjohn56** [comment]
OK, well if the master has them in that's fine.

**Comment by fichtner** [comment]
ok :)

**Comment by marjohn56** [comment]
I've compiled it with the missing config.c and sent it to Kev, waiting for his ack._

**Comment by nivek1612** [comment]
That fixed it cheers

**Comment by fichtner** [comment]
ok, I'll prepare another release then. thanks guys!

**Comment by nivek1612** [comment]
whats the ETA on RC3 ? I'll block out some time to test it

**Comment by fichtner** [comment]
No rc3, 18.7 in the 31st.

**Pull request merged**
