### PR TITLE
Adds support to receive raw-options

### PR DESCRIPTION
**Pull request by noctarius**
The current patch adds raw-options support to the server side and also offers the possibility to send raw-options to a remote DHCPv6 server. This is great, however it is missing the option to receive (or better said use) the answers to those raw-options requested.

This patch adds support to get raw-options send to the environment before the script is called. Raw dhcp options are sent as "raw_dhcp_option_xyz=HEX" where xyz is the number of the option and HEX is the hex-encoded response (similar to the configuration of the server-side, but without the actual colons in between bytes).

### CODE REVIEW

**Comment by marjohn56** [comment]
@noctarius  - Is this patch on top of the RAW options send, and is it working? Do I need to do anything?

**Comment by noctarius** [comment]
It is a patch on top of the original raw-options patch (see the PR base branch), however I'm not sure it works since I didn't have time yet to set up everything and try it together.

**Comment by marjohn56** [comment]
OK, will wait on you for an update.

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
